
# | START: configuration.yaml
# |  PATH: /config/configuration.yaml


# ╭────────────────────╮
# │ CORE
# ╰────────────────────╯ 
default_config:
homeassistant:
  name:                              "Home"
  unit_system:                       "metric"
  temperature_unit:                  "C"
  currency:                          "GBP"
  time_zone:                         "Europe/London"
  latitude:                          !secret home_latitude
  longitude:                         !secret home_longitude
  elevation:                         !secret home_elevation
  packages:                          !include_dir_named packages
  allowlist_external_dirs:
    - /config
    - /config/www
    - /config/www/whatsapp_histories



# ╭────────────────────╮
# │ INCLUDES
# ╰────────────────────╯ 
automation:                          !include automations.yaml
scene:                               !include scenes.yaml
script:                              !include scripts.yaml



# ╭────────────────────╮
# │ FRONTEND
# ╰────────────────────╯ 
lovelace:
  mode: yaml
  resources:                         !include ui/ui_lovelace_resources.yaml
frontend:
  themes:                            !include_dir_merge_named themes
  extra_module_url:                  !include ui/frontend_extra_modules.yaml



# ╭────────────────────╮
# │ INTEGRATIONS
# ╰────────────────────╯ 
lovelace_gen:
powercalc:
whatsapp:
browser_mod:



# ╭────────────────────╮
# │ COMMS
# ╰────────────────────╯ 
sensor:
  - platform: chatreader
    scan_interval: 5


# |   END: configuration.yaml
